"""add activo to huespedes

Revision ID: 898bd84d96aa
Revises: 14a512034752
Create Date: 2026-06-24 16:41:39.256689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898bd84d96aa'
down_revision: Union[str, None] = '14a512034752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('huespedes', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('notificaciones', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true')))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notificaciones', 'activo')
    op.drop_column('huespedes', 'activo')
    # ### end Alembic commands ###
